name: Deploy to CapRover

on:
  push:
    branches:
      - main   # or "main" if your repo uses that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}   # https://captain.server.com
          app: ${{ secrets.CAPROVER_APP }}         # your CapRover app name
          token: ${{ secrets.CAPROVER_TOKEN }}     # App Token from CapRover dashboard
          branch: master                           # which branch to deploy
