name: Build & Deploy to CapRover

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy App to CapRover
        run: |
          caprover deploy \
            --host ${{ secrets.CAPROVER_SERVER }} \
            --appToken ${{ secrets.APP_TOKEN }} \
            --appName ${{ secrets.APP_NAME }}
